version: '2'

services:
 ansibletest:
  build:
   context: .
  container_name: ansible-test
  hostname: ansible_test
  privileged: true
  mem_limit: "1G"
  cpuset: "2"
  command: "/usr/sbin/init"
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - ../app:/var/www/html
  environment:
    - CONTAINER=docker
    - TERM=xterm
  ports:
    - "8130:80"
