---

# Overview: Playbook para probar el módulo de docker service
# Applies to: Development
# Description:
#    Levanta un servicio de docker-compose
- hosts: all
  become: true 
  tags: ['deploy']
  tasks:
    - name: stop docker-compose service
      docker_service: project_src=./devops state=absent 

    - name: start
      docker_service: project_src=./devops build=yes
      register: output

    - name: debug
      debug: var=output verbosity=3
- hosts: all
  become: true
  tags: ['command']
  tasks:
    - name: test
      shell: echo "HELLO PABLO" >> /tmp/test2.txt
- hosts: all
  tags: ['service']
  tasks:
    - name: up init
      shell: /usr/sbin/init
    - shell: echo "finished" >> /tmp/test2.txt 
